apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-pgdump
  namespace: cron-jobs
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: cron-pgdump
              image: cr.yandex/crpoghn06qpit3061gka/cron-pgdump:0.1.3-amd64
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: yandex