package:
  name: cron-pgdump
  version: 0.1.3
  default: true
  files:
    - name: .github/workflows/build-and-push-docker.yml
      templates:
        - "TAG: ${{ env.REGISTRY_IMAGE }}:__VERSION__"
    - name: deployments/cron-job.yaml
      templates:
        - ":__VERSION__-amd64"